AllCops:
  Exclude:
    - 'bundle_bin/*'
    - 'vendor/bundle/**/*'
    - 'db/schema.rb'

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

Style/FileName:
  Exclude:
    - exe/*

Style/RegexpLiteral:
  MaxSlashes: 0
