language: ruby
sudo: false
rvm:
  - 2.2.1
addons:
  postgresql: "9.3"
before_install:
  - gem update bundler
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.travis.yml config/database.yml
- bundle exec rake db:create db:migrate
notifications:
  email:
    - ogataken@gmail.com
branches:
  only:
    - master
